### ISSUE TITLE
ImportError: Cannot import name 'Context' from 'discord_components'

### ISSUE THREAD

**Issue by Isaacyipdeen** [decave27/ButtonPaginator#1]
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from ButtonPaginator import Paginator
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ButtonPaginator/__init__.py", line 1, in <module>
    from .paginator import Paginator
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/ButtonPaginator/paginator.py", line 8, in <module>
    from discord_components import (
ImportError: cannot import name 'Context' from 'discord_components' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord_components/__init__.py)`

**Comment by Cake-dot** [comment]
I have the same issuse

**Comment by decave27** [comment]
I will test and fix

**Comment by Bimi05** [comment]
That is a common error, `discord_components` doesn't have `Context`. At the very top of imports, remove the `Context` from the `discord_components` import and then do: `from commands import Context` and that should do it

**Comment by decave27** [comment]
Fixed
